apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelservice-decode
spec:
  template:
    spec:
      initContainers:
        - name: routing-proxy
          image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.4.0-rc.1
          args:
            - --port=8000
            - --vllm-port=8200
            - --connector=nixlv2
            - --zap-encoder=json
            - --zap-log-level=debug
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace