apiVersion: v1
kind: Pod
metadata:
  name: pvc-debugger
spec:
  containers:
    - name: shell
      image: ubuntu
      command: ["/bin/bash"]
      args: ["-c", "sleep infinity"]
      volumeMounts:
        - name: model-storage
          mountPath: /mnt
  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: model-pvc    # <---- change this to the name of your pvc
  restartPolicy: Never