apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteMany             # <--- Change to ReadWriteOnce if your StorageClass only provides RWO
  resources:
    requests:
      storage: 5Gi              # <--- make sure your PV has enough storage for this claim
  volumeName: model-pv          # <--- change this to reflect the name of the PV
  storageClass: standard        # <--- change this to reflect the storage class of your PV
