---
# Source: llm-d-modelservice/templates/epp-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-sim-llm-d-modelservice-epp-sa
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.4
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: llm-d-modelservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-sim-llm-d-modelservice-sa
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.4
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: llm-d-modelservice/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-sim-llm-d-modelservice-epp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-read
subjects:
- kind: ServiceAccount
  name: vllm-sim-llm-d-modelservice-epp-sa
---
# Source: llm-d-modelservice/templates/epp-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vllm-sim-llm-d-modelservice-epp-service
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.4
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9002
      targetPort: 9002
      protocol: TCP
      appProtocol: http2
  selector:
    llm-d.ai/epp: vllm-sim-llm-d-modelservice-epp
---
# Source: llm-d-modelservice/templates/decode-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-sim-llm-d-modelservice-decode
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.4
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: vllm-sim-llm-d-modelservice
      llm-d.ai/role: decode
  template:
    metadata:
      labels:
        llm-d.ai/inferenceServing: "true"
        llm-d.ai/model: vllm-sim-llm-d-modelservice
        llm-d.ai/role: decode
    spec:
      initContainers:
        - name: routing-proxy
          args:
            - --port=8000
            - --vllm-port=8200
            - --connector=nixlv2
            - -v=5
          image: ghcr.io/llm-d/llm-d-routing-sidecar:0.0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources: {}
          restartPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true

      serviceAccountName: vllm-sim-llm-d-modelservice-sa
      volumes:
        - name: model-storage
          emptyDir:
            sizeLimit: 5Mi
      containers:
        - name: vllm
          image: ghcr.io/llm-d/llm-d-inference-sim:0.0.4
          args:
          - "random"
          - --port
          - "8200"
          - --model
          - random
          - --port
          - "8200"
          env:
          - name: DP_SIZE
            value: "1"
          - name: TP_SIZE
            value: "1"
          - name: DP_SIZE_LOCAL
            value: "1"
          - name: HF_HOME
            value: /model-cache

          resources:
            limits:
              {}
            requests:
              {}
          volumeMounts:
          - name: model-storage
            mountPath: /model-cache
---
# Source: llm-d-modelservice/templates/epp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-sim-llm-d-modelservice-epp
  labels:
    llm-d.ai/epp: vllm-sim-llm-d-modelservice-epp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/epp: vllm-sim-llm-d-modelservice-epp
  template:
    metadata:
      labels:
        llm-d.ai/epp: vllm-sim-llm-d-modelservice-epp
    spec:
      containers:
      - name: epp
        imagePullPolicy: Always
        image: ghcr.io/llm-d/llm-d-inference-scheduler:0.0.3
        args:
        - --poolName
        - vllm-sim-llm-d-modelservice-inference-pool
        - --poolNamespace
        - default
        - -v
        - "6"
        - --zap-encoder
        - json
        - --grpcPort
        - "9002"
        - --grpcHealthPort
        - "9003"
        # using defaults from https://github.com/llm-d/llm-d-deployer/blob/main/charts/llm-d/values.yaml#L563-L603
        env:
        - name: ENABLE_KVCACHE_AWARE_SCORER
          value: "false"
        - name: ENABLE_LOAD_AWARE_SCORER
          value: "true"
        - name: ENABLE_PREFIX_AWARE_SCORER
          value: "true"
        - name: ENABLE_SESSION_AWARE_SCORER
          value: "false"
        - name: KVCACHE_AWARE_SCORER_WEIGHT
          value: "1"
        - name: KVCACHE_INDEXER_REDIS_ADDR
        - name: LOAD_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PD_ENABLED
          value: "false"
        - name: PD_PROMPT_LEN_THRESHOLD
          value: "10"
        - name: PREFILL_ENABLE_KVCACHE_AWARE_SCORER
          value: "false"
        - name: PREFILL_ENABLE_LOAD_AWARE_SCORER
          value: "false"
        - name: PREFILL_ENABLE_PREFIX_AWARE_SCORER
          value: "false"
        - name: PREFILL_ENABLE_SESSION_AWARE_SCORER
          value: "false"
        - name: PREFILL_KVCACHE_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_KVCACHE_INDEXER_REDIS_ADDR
        - name: PREFILL_LOAD_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_PREFIX_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_SESSION_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFIX_AWARE_SCORER_WEIGHT
          value: "2"
        - name: SESSION_AWARE_SCORER_WEIGHT
          value: "1"
        ports:
        - containerPort: 9002
          name: grpc
          protocol: TCP
        - containerPort: 9003
          name: grpc-health
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
      serviceAccount: vllm-sim-llm-d-modelservice-epp-sa
      serviceAccountName: vllm-sim-llm-d-modelservice-epp-sa
---
# Source: llm-d-modelservice/templates/prefill-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-sim-llm-d-modelservice-prefill
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.4
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: vllm-sim-llm-d-modelservice
      llm-d.ai/role: prefill
  template:
    metadata:
      labels:
        llm-d.ai/inferenceServing: "true"
        llm-d.ai/model: vllm-sim-llm-d-modelservice
        llm-d.ai/role: prefill
    spec:

      serviceAccountName: vllm-sim-llm-d-modelservice-sa
      volumes:
        - name: model-storage
          emptyDir:
            sizeLimit: 5Mi
      containers:
        - name: vllm
          image: ghcr.io/llm-d/llm-d-inference-sim:0.0.4
          args:
          - "random"
          - --port
          - "8000"
          - --model
          - random
          - --port
          - "8000"
          env:
          - name: DP_SIZE
            value: "1"
          - name: TP_SIZE
            value: "1"
          - name: DP_SIZE_LOCAL
            value: "1"
          - name: HF_HOME
            value: /model-cache

          resources:
            limits:
              {}
            requests:
              {}
          volumeMounts:
          - name: model-storage
            mountPath: /model-cache
---
# Source: llm-d-modelservice/templates/routing.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vllm-sim-llm-d-modelservice-http-route
  namespace: default
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.4
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: llm-d-inference-gateway
  rules:
  - backendRefs:
    - group: inference.networking.x-k8s.io
      kind: InferencePool
      name: vllm-sim-llm-d-modelservice-inference-pool
      port: 8000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
      headers:
      - name: x-model-name
        type: Exact
        value: random
---
# Source: llm-d-modelservice/templates/routing.yaml
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: vllm-sim-llm-d-modelservice-inference-pool
  namespace: default
spec:
  extensionRef:
    failureMode: FailClose
    group: ""
    kind: Service
    name: vllm-sim-llm-d-modelservice-epp-service
  selector:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: vllm-sim-llm-d-modelservice
  targetPortNumber: 8000
