---
# Source: llm-d-modelservice/templates/epp-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-sim-llm-d-modelservice-epp
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.19
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: llm-d-modelservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-sim-llm-d-modelservice
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.19
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: llm-d-modelservice/templates/epp-plugin-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-sim-llm-d-modelservice-epp
  namespace: e2e-solution
data:
  default-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: prefix-cache-scorer
      parameters:
        hashBlockSize: 5
        maxPrefixBlocksToMatch: 256
        lruCapacityPerServer: 31250
    - type: decode-filter
    - type: max-score-picker
    - type: single-profile-handler
    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: decode-filter
      - pluginRef: max-score-picker
      - pluginRef: prefix-cache-scorer
        weight: 50
  prefix-cache-tracking-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
      - type: single-profile-handler
      - type: decode-filter
      - type: prefix-cache-scorer
        parameters:
          mode: cache_tracking
          indexerConfig:
            tokenProcessorConfig:
              blockSize: 64                         # must match vLLM block size if not default (16)
              hashSeed: "42"                        # must match PYTHONHASHSEED in vLLM pods
            kvBlockIndexConfig:
              enableMetrics: true                   # enable kv-block index metrics (prometheus)
              metricsLoggingInterval: 60000000000   # log kv-block metrics as well (1m in nanoseconds)
      - type: kv-cache-scorer # kv-cache-utilization
      - type: queue-scorer
      - type: max-score-picker
    schedulingProfiles:
      - name: default
        plugins:
          - pluginRef: decode-filter
          - pluginRef: prefix-cache-scorer
            weight: 3.0
          - pluginRef: kv-cache-scorer
            weight: 1.0
          - pluginRef: queue-scorer
            weight: 1.0
          - pluginRef: max-score-picker
  prefix-estimate-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: single-profile-handler
    - type: decode-filter
    - type: prefix-cache-scorer
    - type: load-aware-scorer
    - type: max-score-picker
    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: decode-filter
      - pluginRef: prefix-cache-scorer
        weight: 2.0
      - pluginRef: load-aware-scorer
        weight: 1.0
      - pluginRef: max-score-picker
  default-pd-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: prefill-header-handler
    - type: prefix-cache-scorer
      parameters:
        hashBlockSize: 5
        maxPrefixBlocksToMatch: 256
        lruCapacityPerServer: 31250
    - type: prefill-filter
    - type: decode-filter
    - type: max-score-picker
    - type: pd-profile-handler
      parameters:
        threshold: 10
        hashBlockSize: 5
    schedulingProfiles:
    - name: prefill
      plugins:
      - pluginRef: prefill-filter
      - pluginRef: max-score-picker
      - pluginRef: prefix-cache-scorer
        weight: 50
    - name: decode
      plugins:
      - pluginRef: decode-filter
      - pluginRef: max-score-picker
      - pluginRef: prefix-cache-scorer
        weight: 50
---
# Source: llm-d-modelservice/templates/epp-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vllm-sim-llm-d-modelservice-epp
rules:
- apiGroups:
  - inference.networking.x-k8s.io
  resources:
  - inferencemodels
  - inferencepools
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
# Source: llm-d-modelservice/templates/epp-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-sim-llm-d-modelservice-epp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vllm-sim-llm-d-modelservice-epp
subjects:
- kind: ServiceAccount
  name: vllm-sim-llm-d-modelservice-epp
---
# Source: llm-d-modelservice/templates/epp-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vllm-sim-llm-d-modelservice-epp
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.19
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: grpc-ext-proc
      port: 9002
      targetPort: 9002
      protocol: TCP
      appProtocol: http2
  selector:
    llm-d.ai/epp: vllm-sim-llm-d-modelservice-epp
---
# Source: llm-d-modelservice/templates/decode-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-sim-llm-d-modelservice-decode
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.19
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: vllm-sim-llm-d-modelservice
      llm-d.ai/role: decode
  template:
    metadata:
      labels:
        llm-d.ai/inferenceServing: "true"
        llm-d.ai/model: vllm-sim-llm-d-modelservice
        llm-d.ai/role: decode
    spec:
      initContainers:
        - name: routing-proxy
          args:
            - --port=8000
            - --vllm-port=8200
            - --connector=nixlv2
            - -v=5
            - --secure-proxy=false
          image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0-rc2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources: {}
          restartPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
    
      serviceAccountName: vllm-sim-llm-d-modelservice
      volumes:
        - emptyDir: {}
          name: metrics-volume
        - name: model-storage
          emptyDir: 
            sizeLimit: 5Mi
      containers:
        - name: vllm
          image: ghcr.io/llm-d/llm-d-inference-sim:v0.3.0
          
          args:
            - --model
            - "random/model"
            - --port
            - "8200"
            - --served-model-name
            - random/model
          env:
          - name: DP_SIZE
            value: "1"
          - name: TP_SIZE
            value: "1"
          
          - name: HF_HOME
            value: /model-cache
          
          resources:
            limits:
              {}
            requests:
              {}
          
          volumeMounts:
            - name: model-storage
              mountPath: /model-cache
---
# Source: llm-d-modelservice/templates/epp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-sim-llm-d-modelservice-epp
  labels:
    llm-d.ai/epp: vllm-sim-llm-d-modelservice-epp
  namespace: e2e-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/epp: vllm-sim-llm-d-modelservice-epp
  template:
    metadata:
      labels:
        llm-d.ai/epp: vllm-sim-llm-d-modelservice-epp
    spec:
      containers:
      - name: epp
        imagePullPolicy: Always
        image: ghcr.io/llm-d/llm-d-inference-scheduler:v0.2.0
        args:
        - --poolName
        - vllm-sim-llm-d-modelservice
        - --poolNamespace
        - e2e-solution
        - -v
        - "6"
        - --zap-encoder
        - json
        - --grpcPort
        - "9002"
        - --grpcHealthPort
        - "9003"
        - "-configFile"
        - "config/default-config.yaml"
        ports:
        - containerPort: 9002
          name: grpc
          protocol: TCP
        - containerPort: 9003
          name: grpc-health
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        volumeMounts:
          - name: plugins-config-volume
            mountPath: "/config"
      volumes:
      - name: plugins-config-volume
        configMap:
          name: vllm-sim-llm-d-modelservice-epp
      serviceAccount: vllm-sim-llm-d-modelservice-epp
      serviceAccountName: vllm-sim-llm-d-modelservice-epp
---
# Source: llm-d-modelservice/templates/prefill-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-sim-llm-d-modelservice-prefill
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.19
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: vllm-sim-llm-d-modelservice
      llm-d.ai/role: prefill
  template:
    metadata:
      labels:
        llm-d.ai/inferenceServing: "true"
        llm-d.ai/model: vllm-sim-llm-d-modelservice
        llm-d.ai/role: prefill
    spec:
    
      serviceAccountName: vllm-sim-llm-d-modelservice
      volumes:
        - emptyDir: {}
          name: metrics-volume
        - name: model-storage
          emptyDir: 
            sizeLimit: 5Mi
      containers:
        - name: vllm
          image: ghcr.io/llm-d/llm-d-inference-sim:v0.3.0
          
          args:
            - --model
            - "random/model"
            - --port
            - "8000"
            - --served-model-name
            - random/model
          env:
          - name: DP_SIZE
            value: "1"
          - name: TP_SIZE
            value: "1"
          
          - name: HF_HOME
            value: /model-cache
          
          resources:
            limits:
              {}
            requests:
              {}
          
          volumeMounts:
            - name: model-storage
              mountPath: /model-cache
---
# Source: llm-d-modelservice/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vllm-sim-llm-d-modelservice
  namespace: e2e-solution
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.19
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: inference-gateway
  rules:
    - timeouts:
        backendRequest: "0s"
        request: "0s"
      backendRefs:
      - group: inference.networking.x-k8s.io
        kind: InferencePool
        name: vllm-sim-llm-d-modelservice
        port: 8000
        weight: 1
      matches:
      - headers:
        - name: x-model-name
          type: Exact
          value: random/model
        path:
          type: PathPrefix
          value: /
---
# Source: llm-d-modelservice/templates/inferencepool.yaml
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: vllm-sim-llm-d-modelservice
  namespace: e2e-solution
spec:
  extensionRef:
    failureMode: FailClose
    group: ""
    kind: Service
    name: vllm-sim-llm-d-modelservice-epp
  selector:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: vllm-sim-llm-d-modelservice
  targetPortNumber: 8000
