# Intel Gaudi configuration using imageDefault mode
# This configuration lets the chart handle most vLLM parameters automatically

modelArtifacts:
  name: meta-llama/Llama-3.1-8B-Instruct
  uri: "hf://meta-llama/Llama-3.1-8B-Instruct"
  size: 10Gi

accelerator:
  type: "intel-gaudi"

# Routing configuration
routing:
  proxy:
    enabled: false

# Decode pod configuration for Intel XPU - simplified with imageDefault
decode:
  create: true
  replicas: 1
  containers:
  - name: "vllm"
    # Use custom vLLM image for Gaudi for now
    image: "opea/vllm-gaudi"

    # Use imageDefault mode - chart will generate basic vLLM command automatically
    modelCommand: "imageDefault"

    # Only specify Gaudi specific arguments that differ from defaults
    args:
    - --block-size=128
    - --max-num-seqs=256
    - --max-seq-len-to-capture=2048
    - --max-model-len=2048
    - --max-num-batched-token=16000
    env:
    - name: OMPI_MCA_btl_vader_single_copy_mechanism
      value: "none"
    ports:
      - containerPort: 8200
        protocol: TCP

    mountModelVolume: true

# Disable prefill for simple XPU example
prefill:
  create: false

# When true, use LeaderWorkerSet for multi-node XPU setups
multinode: false
