{{- if and .Values.routing.epp.create (hasKey .Values.routing.epp "pluginsCustomConfig") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-d-modelservice.eppConfigName" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- .Values.routing.epp.pluginsCustomConfig | toYaml | nindent 2 }}
{{- end}}
