{{- if and .Values.endpointPicker.create .Values.endpointPicker.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.endpointPicker.role.name | default "default-epp-rolebinding" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.endpointPicker.role.name | default "default-epp-role" }}
subjects:
- kind: ServiceAccount
  name: {{ include "llm-d-modelservice.eppServiceAccountName" . }}
{{- end }}
