{{- if and .Values.routing.epp.create .Values.routing.epp.pluginsConfigFile -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-d-modelservice.eppConfigName" . }}
  namespace: {{ .Release.Namespace }}
data:
  default-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: prefix-cache-scorer
      parameters:
        hashBlockSize: 5
        maxPrefixBlocksToMatch: 256
        lruCapacityPerServer: 31250
    - type: decode-filter
    - type: max-score-picker
    - type: single-profile-handler
    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: decode-filter
      - pluginRef: max-score-picker
      - pluginRef: prefix-cache-scorer
        weight: 50
  prefix-cache-tracking-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: single-profile-handler
    - type: decode-filter
    - type: prefix-cache-scorer
      parameters:
        mode: cache_tracking
        kvCacheRedisAddr: ${REDIS_HOST}:${REDIS_PORT}
    - type: load-aware-scorer
    - type: max-score-picker
    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: decode-filter
      - pluginRef: prefix-cache-scorer
        weight: 2.0
      - pluginRef: load-aware-scorer
        weight: 1.0
      - pluginRef: max-score-picker
  prefix-estimate-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: single-profile-handler
    - type: decode-filter
    - type: prefix-cache-scorer
    - type: load-aware-scorer
    - type: max-score-picker
    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: decode-filter
      - pluginRef: prefix-cache-scorer
        weight: 2.0
      - pluginRef: load-aware-scorer
        weight: 1.0
      - pluginRef: max-score-picker
  default-pd-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: prefill-header-handler
    - type: prefix-cache-scorer
      parameters:
        hashBlockSize: 5
        maxPrefixBlocksToMatch: 256
        lruCapacityPerServer: 31250
    - type: prefill-filter
    - type: decode-filter
    - type: max-score-picker
    - type: pd-profile-handler
      parameters:
        threshold: 10
        hashBlockSize: 5
    schedulingProfiles:
    - name: prefill
      plugins:
      - pluginRef: prefill-filter
      - pluginRef: max-score-picker
      - pluginRef: prefix-cache-scorer
        weight: 50
    - name: decode
      plugins:
      - pluginRef: decode-filter
      - pluginRef: max-score-picker
      - pluginRef: prefix-cache-scorer
        weight: 50
  {{- if (hasKey .Values.routing.epp "pluginsCustomConfig") }}
  {{- .Values.routing.epp.pluginsCustomConfig | toYaml | nindent 2 }}
  {{- end }}
{{- end}}
