
{{- if .Values.routing.httpRoute.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "llm-d-modelservice.httpRouteName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  {{- with .Values.routing.parentRefs }}
  parentRefs:
  {{- . | toYaml | nindent 2}}
  {{- end }}
  {{- if .Values.routing.httpRoute.rules }}
  rules:
  {{- with .Values.routing.httpRoute.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- else }}
  rules:
    - timeouts:
        backendRequest: "0s"
        request: "0s"
      backendRefs:
      - group: inference.networking.x-k8s.io
        kind: InferencePool
        name: {{ include "llm-d-modelservice.inferencePoolName" . }}
        port: {{ .Values.routing.servicePort  }}
        weight: 1
      {{- if .Values.routing.httpRoute.matches }}
      matches:
      {{- with .Values.routing.httpRoute.matches }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- else }}
      matches:
      - path:
          type: PathPrefix
          value: /
      {{- end -}}
  {{- end }}
{{- end }}
