{{- if .Values.routing.inferenceModel.create }}
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  labels:
    {{- include "llm-d-modelservice.pdlabels" . | nindent 4 }}
  name: {{ include "llm-d-modelservice.inferenceModelName" . }}
spec:
  {{- if .Values.routing.inferenceModel.criticality }}
  criticality: {{ .Values.routing.inferenceModel.criticality }}
  {{- end}}
  modelName: {{ .Values.routing.modelName }}
  poolRef:
    name: {{ include "llm-d-modelservice.inferencePoolName" . }}
{{- end }}
