{{- if and .Values.prefill.create .Values.multinode }}
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: {{ include "llm-d-modelservice.prefillName" . }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
    {{- include "llm-d-modelservice.prefilllabels" . | nindent 4 }}
  {{- if or .Values.prefill.subGroupExclusiveTopology .Values.prefill.annotations }}
  annotations:
  {{- if .Values.prefill.subGroupExclusiveTopology }}
    leaderworkerset.sigs.k8s.io/subgroup-exclusive-topology: kubernetes.io/hostname
  {{- end }}
  {{- if .Values.prefill.annotations }}
    {{ toYaml .Values.prefill.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if not .Values.prefill.autoscaling.enabled }}
  replicas: {{ ternary .Values.prefill.replicas 1 (hasKey .Values.prefill "replicas") }}
  {{- end }}
  leaderWorkerTemplate:
    size: {{ int (include "llm-d-modelservice.dataParallelism" .Values.prefill.parallelism) }}
    {{- if .Values.prefill.subGroupPolicy }}
    subGroupPolicy:
    {{- toYaml .Values.prefill.subGroupPolicy | nindent 6 }}
    {{-  end }}

    # no sidecar so no need to specify leader separately

    workerTemplate:
      metadata:
        labels:
          {{- include "llm-d-modelservice.prefilllabels" . | nindent 10 }}
        {{- if or .Values.prefill.subGroupExclusiveTopology .Values.prefill.annotations }}
        annotations:
        {{- if .Values.prefill.subGroupExclusiveTopology }}
          leaderworkerset.sigs.k8s.io/subgroup-exclusive-topology: kubernetes.io/hostname
        {{- end }}
        {{- if .Values.prefill.annotations }}
          {{ toYaml .Values.prefill.annotations | nindent 10 }}
          {{- end }}
        {{- end }}
      spec:
        {{- if hasKey .Values.prefill "hostIPC" }}
        hostIPC: {{ .Values.prefill.hostIPC }}
        {{- end }}
        {{- if hasKey .Values.prefill "hostPID" }}
        hostPID: {{ .Values.prefill.hostPID }}
        {{- end }}
        {{- (include "llm-d-modelservice.modelPod" (dict "pdSpec" .Values.prefill "Values" .Values "Release" .Release "Chart" .Chart)) | nindent 6 }}
        {{- with .Values.prefill.containers }}
        containers:
          {{- range . }}
        {{- (include "llm-d-modelservice.container" (dict "role" "prefill" "container" . "parallelism" $.Values.prefill.parallelism "Values" $.Values "Release" $.Release "Chart" $.Chart)) | nindent 8 }}
          {{- end }}
        {{- end }}

{{- end }}
