{{- if and .Values.prefill.create .Values.prefill.monitoring.podmonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "llm-d-modelservice.prefillName" . }}-podmonitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: prefill
  {{- with .Values.prefill.monitoring.podmonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.prefill.monitoring.podmonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "llm-d-modelservice.prefilllabels" . | nindent 6 }}
  podMetricsEndpoints:
  # For prefill, this is port 8000. Must use port name.
  - port: {{ .Values.prefill.monitoring.podmonitor.portName | default "metrics" | quote }}
    path: {{ .Values.prefill.monitoring.podmonitor.path | default "/metrics" }}
    interval: {{ .Values.prefill.monitoring.podmonitor.interval | default "30s" }}
    {{- with .Values.prefill.monitoring.podmonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.prefill.monitoring.podmonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.prefill.monitoring.podmonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.prefill.monitoring.podmonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
