apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: gpu-claim-template
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: resource.k8s.io
      kind: ResourceClaimParameters
      name: gpu-parameters